server:
  port: 20480

spring:
  application.name: otp-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: angularpay
      username: service_account
      password: service_account_password
      authentication-database: angularpay

angularpay:
  defaultOtpExpiryInSeconds: 180
  redis:
    host: localhost
    port: 6379
    timeout: 10000
